package zchttp

import (
	"fmt"
	"log/slog"
	"reflect"
	"strings"
)

// checkUnsupportedDefaults 递归遍历结构体类型树，检测三种 default 误用：
//
//  1. 类型不支持：default 写在 time.Time / struct 等非标量类型上，注册阶段即不填充。
//  2. 值类型无法到达：default 写在值类型字段（int/string/bool）上，但所在 struct
//     非"值嵌套可达"（即路径上存在指针/切片/map 边），请求阶段永不填充。
//  3. 指针类型无法到达：default 写在指针字段（*int/*string/*bool）上，但所在 struct
//     非"默认值可达"（即 applyDefaults 递归无法穿透的路径，如 map 值类型为切片），
//     请求阶段永不填充。
//
// viaValue 表示当前 struct 是否通过纯值类型链可达（含义同 walkTypeUsage），
// 顶层 Req/Res 为 true。
// viaDefaults 表示当前 struct 是否可被 applyDefaults 递归到达（与 viaValue 不同：
// 指针/切片/数组不打断 viaDefaults，但 map 值类型为切片/数组时会打断）。
// visiting 用于自引用循环检测。
// method/path 为接口路由信息，handlerName/handlerFile/handlerLine 为 handler 源码位置
// （闭包 handler 的 handlerFile 为 "<autogenerated>"，此时降级使用 handlerName）。
func checkUnsupportedDefaults(t reflect.Type, viaValue bool, viaDefaults bool, method, path, handlerName, handlerFile string, handlerLine int, visiting map[reflect.Type]bool) {
	t = derefType(t)
	if t.Kind() != reflect.Struct {
		return
	}
	if visiting[t] {
		return
	}
	visiting[t] = true
	defer delete(visiting, t)

	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue
		}
		if f.Anonymous && f.Type == metaType {
			continue
		}

		handlerLoc := fmt.Sprintf("%s:%d", handlerFile, handlerLine)
		if handlerFile == "<autogenerated>" {
			handlerLoc = handlerName
		}

		_, hasDefault := f.Tag.Lookup("default")
		if hasDefault {
			if !isDefaultSupported(f.Type) {
				// 情况 1：类型不支持（如 time.Time / struct 类型）
				slog.Warn("default tag on unsupported type, ignored",
					"route", method+" "+path,
					"handler", handlerLoc,
					"struct", t.Name(),
					"field", f.Name,
					"type", f.Type.String(),
				)
			} else if f.Type.Kind() != reflect.Ptr && !viaValue {
				// 情况 2：值类型字段在非"值嵌套可达"的 struct 中。
				// 注册阶段因路径上有 nil 指针/切片/map 也无法到达。
				slog.Warn("default tag on value field in non-value-reachable struct, never applied",
					"route", method+" "+path,
					"handler", handlerLoc,
					"struct", t.Name(),
					"field", f.Name,
					"type", f.Type.String(),
				)
			} else if f.Type.Kind() == reflect.Ptr && !viaDefaults {
				// 情况 3：指针字段在非"默认值可达"的 struct 中。
				// 如 map 值类型为切片/数组时，applyDefaults 无法穿透，请求阶段永不填充。
				slog.Warn("default tag on pointer field in non-defaults-reachable struct, never applied",
					"route", method+" "+path,
					"handler", handlerLoc,
					"struct", t.Name(),
					"field", f.Name,
					"type", f.Type.String(),
				)
			}
		}

		// 递归进入嵌套结构体：viaValue/viaDefaults 传播规则：
		// - Ptr：viaValue=false，viaDefaults 不变（applyDefaults 可跟随非 nil 指针）
		// - Struct：两者均不变
		// - Slice/Array：viaValue=false，viaDefaults 不变（applyDefaults 可遍历切片元素）
		// - Map：viaValue=false，viaDefaults 仅当值类型为 Struct 或 *Struct 时不变，
		//   若值类型为 Slice/Array 则 viaDefaults=false（applyDefaults 无法穿透）
		ft := f.Type
		switch ft.Kind() {
		case reflect.Ptr:
			checkUnsupportedDefaults(ft.Elem(), false, viaDefaults, method, path, handlerName, handlerFile, handlerLine, visiting)
		case reflect.Struct:
			checkUnsupportedDefaults(ft, viaValue, viaDefaults, method, path, handlerName, handlerFile, handlerLine, visiting)
		case reflect.Slice, reflect.Array:
			elem := ft.Elem()
			if elem.Kind() == reflect.Ptr {
				elem = elem.Elem()
			}
			if elem.Kind() == reflect.Slice || elem.Kind() == reflect.Array || elem.Kind() == reflect.Map {
				// 多层容器（[][]Struct、[]map[K]Struct、[]map[K][]Struct 等）：元素仍为容器，
				// applyDefaults 无法穿透，继续下探直到 struct 元素并传递 viaDefaults=false，
				// 使其中带 default 的字段触发启动期警告（与 map 分支的警告行为对齐）
				for elem.Kind() == reflect.Slice || elem.Kind() == reflect.Array || elem.Kind() == reflect.Map {
					elem = elem.Elem()
					if elem.Kind() == reflect.Ptr {
						elem = elem.Elem()
					}
				}
				checkUnsupportedDefaults(elem, false, false, method, path, handlerName, handlerFile, handlerLine, visiting)
			} else {
				checkUnsupportedDefaults(elem, false, viaDefaults, method, path, handlerName, handlerFile, handlerLine, visiting)
			}
		case reflect.Map:
			elem := ft.Elem()
			if elem.Kind() == reflect.Ptr {
				checkUnsupportedDefaults(elem.Elem(), false, viaDefaults, method, path, handlerName, handlerFile, handlerLine, visiting)
			} else if elem.Kind() == reflect.Slice || elem.Kind() == reflect.Array {
				// map 值类型为切片/数组：applyDefaults 无法穿透，viaDefaults=false
				subElem := elem.Elem()
				if subElem.Kind() == reflect.Ptr {
					checkUnsupportedDefaults(subElem.Elem(), false, false, method, path, handlerName, handlerFile, handlerLine, visiting)
				} else {
					checkUnsupportedDefaults(subElem, false, false, method, path, handlerName, handlerFile, handlerLine, visiting)
				}
			} else {
				checkUnsupportedDefaults(elem, false, viaDefaults, method, path, handlerName, handlerFile, handlerLine, visiting)
			}
		default:
			// Interface / Func / Chan / UnsafePointer 等无法反射出 struct，无需处理
		}
	}
}

// applyDefaults 递归遍历结构体树，为带 default 标签的字段初始化默认值。
// 注册阶段（requestPhase=false）：对模板中的所有零值字段填充默认值。
// 请求阶段（requestPhase=true）：仅递归进入动态创建的子元素（切片/数组/map/nested ptr），
// 并仅对 nil 指针字段填充默认值（值类型如 int/string 不填充，避免覆盖用户显式传入的零值）。
// meta 为注册阶段预计算的 structMeta，直接遍历其 fields 避免请求阶段反射。
func applyDefaults(reqPtr reflect.Value, meta structMeta, requestPhase ...bool) {
	rp := len(requestPhase) > 0 && requestPhase[0]
	visiting := acquireVisitMap()
	applyDefaultsWithVisiting(reqPtr, meta, rp, visiting)
	releaseVisitMap(visiting)
}

// applyDefaultsWithVisiting 是 applyDefaults 的内部实现，携带 visiting map 用于运行时循环检测。
// visiting 按 visitKey（指针地址+类型）追踪已访问的实例，避免自引用结构体导致栈溢出。
func applyDefaultsWithVisiting(reqPtr reflect.Value, meta structMeta, rp bool, visiting map[visitKey]bool) {
	elem := reqPtr.Elem()
	if elem.Kind() != reflect.Struct {
		return
	}

	// 运行时循环检测：若当前结构体实例已访问过，停止递归，避免自引用导致栈溢出
	key := visitKey{ptr: reqPtr.Pointer(), typ: elem.Type()}
	if visiting == nil {
		visiting = make(map[visitKey]bool)
	}
	if visiting[key] {
		return
	}
	visiting[key] = true
	defer delete(visiting, key)

	for i := range meta.fields {
		fm := &meta.fields[i]
		fv := fieldByIndex(elem, fm.indices)

		// 决定是否填充默认值：
		// - 注册阶段：所有零值字段均填充
		// - 请求阶段：仅填充 nil 指针字段，值类型零值可能来自用户显式传入，跳过
		var shouldFill bool
		if !rp {
			shouldFill = fm.hasDefault && fv.CanSet() && fv.IsZero()
		} else {
			shouldFill = fm.hasDefault && fv.CanSet() && fv.Kind() == reflect.Ptr && fv.IsNil()
		}
		if shouldFill {
			var values []string
			if fm.isSlice {
				// 切片默认值以逗号分隔，如 default:"a,b,c"。
				// Trim 后为空（default:""、default:" "、default:",,,"）视为空切片，
				// 而非含单个空元素的切片（与绑定语义一致，空默认值 = 无元素）
				trimmed := strings.TrimSpace(fm.defaultVal)
				trimmed = strings.Trim(trimmed, ",")
				if trimmed != "" {
					values = strings.Split(trimmed, ",")
				}
			} else {
				values = []string{strings.TrimSpace(fm.defaultVal)}
			}
			// 尽力填充，转换失败则跳过（time.Time 复用预解析的 time_format/时区）
			_ = setFieldValue(fv, values, fm.timeFormat, fm.timeLocation)
		}

		// 递归进入嵌套结构体/指针/切片/map 字段
		subV := fv
		if subV.Kind() == reflect.Ptr {
			if subV.IsNil() {
				continue
			}
			subV = subV.Elem()
		}
		if subV.Kind() == reflect.Struct {
			subMeta := cachedStructMeta(subV.Type())
			applyDefaultsWithVisiting(subV.Addr(), subMeta, rp, visiting)
		} else if subV.Kind() == reflect.Slice {
			// 结构体切片/结构体指针切片：递归填充每个元素中带 default 标签的字段
			elemType := subV.Type().Elem()
			isPtrElem := elemType.Kind() == reflect.Ptr
			if isPtrElem {
				elemType = elemType.Elem()
			}
			if elemType.Kind() == reflect.Struct {
				subMeta := cachedStructMeta(elemType)
				for i := 0; i < subV.Len(); i++ {
					elem := subV.Index(i)
					if isPtrElem {
						if elem.IsNil() {
							continue
						}
						elem = elem.Elem()
					}
					applyDefaultsWithVisiting(elem.Addr(), subMeta, rp, visiting)
				}
			}
		} else if subV.Kind() == reflect.Array {
			// 数组容器：与切片相同处理，递归填充每个元素中带 default 标签的字段
			elemType := subV.Type().Elem()
			isPtrElem := elemType.Kind() == reflect.Ptr
			if isPtrElem {
				elemType = elemType.Elem()
			}
			if elemType.Kind() == reflect.Struct {
				subMeta := cachedStructMeta(elemType)
				for i := 0; i < subV.Len(); i++ {
					elem := subV.Index(i)
					if isPtrElem {
						if elem.IsNil() {
							continue
						}
						elem = elem.Elem()
					}
					applyDefaultsWithVisiting(elem.Addr(), subMeta, rp, visiting)
				}
			}
		} else if subV.Kind() == reflect.Map {
			// map[K]Struct / map[K]*Struct：递归填充每个 value 中带 default 标签的字段
			valType := subV.Type().Elem()
			isPtrVal := valType.Kind() == reflect.Ptr
			if isPtrVal {
				valType = valType.Elem()
			}
			if valType.Kind() == reflect.Struct {
				// 对 map 自身做循环检测：自引用结构体经 valCopy 复制后 map 字段仍共享同一底层 map，
				// 若再次遇到同一 map 则跳过，防止无限递归
				mapKey := visitKey{ptr: subV.Pointer(), typ: subV.Type()}
				if visiting[mapKey] {
					continue
				}
				visiting[mapKey] = true
				subMeta := cachedStructMeta(valType)
				for _, key := range subV.MapKeys() {
					val := subV.MapIndex(key)
					if isPtrVal {
						if val.IsNil() {
							continue
						}
						// 对指针值做循环检测：同一指针可能经不同路径再次被处理
						ptrKey := visitKey{ptr: val.Pointer(), typ: valType}
						if visiting[ptrKey] {
							continue
						}
						visiting[ptrKey] = true
						val = val.Elem()
					}
					// MapIndex 返回的值不可寻址，需复制一份再调用 applyDefaults
					valCopy := reflect.New(valType).Elem()
					valCopy.Set(val)
					applyDefaultsWithVisiting(valCopy.Addr(), subMeta, rp, visiting)
					// 写回 map：值类型用 SetMapIndex，指针类型通过 pointee 写回
					if isPtrVal {
						subV.MapIndex(key).Elem().Set(valCopy)
					} else {
						subV.SetMapIndex(key, valCopy)
					}
				}
			}
		}
	}
}

// deepCopyDefaults 递归深拷贝结构体树中所有指针/切片/map 字段，确保并发请求间不共享底层内存。
// 在 ServeHTTP 中，模板浅拷贝后调用此函数完成深拷贝。
// 注意：本函数的容器分支必须与 applyDefaultsWithVisiting 的容器分支保持对齐（Struct/Ptr/Slice/Map/Array）。
// 若 applyDefaults 支持新容器类型（如数组），必须同步在本函数补充对应分支，否则并发请求间会共享引用导致数据污染。
// Interface 分支为防御性处理：applyDefaults 不穿透接口字段，但深拷贝需断开 any 动态值中的引用，
// 避免未来 default 白名单放开容器/any 后静默漏判。
func deepCopyDefaults(v reflect.Value) {
	switch v.Kind() {
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			deepCopyDefaults(v.Field(i))
		}
	case reflect.Ptr:
		if !v.IsNil() {
			newPtr := reflect.New(v.Type().Elem())
			newPtr.Elem().Set(v.Elem())
			v.Set(newPtr)
			// 递归拷贝指针指向的元素（struct/slice/map），而非指针本身，避免无限递归
			deepCopyDefaults(v.Elem())
		}
	case reflect.Slice:
		if !v.IsNil() {
			newSlice := reflect.MakeSlice(v.Type(), v.Len(), v.Cap())
			reflect.Copy(newSlice, v)
			v.Set(newSlice)
			for i := 0; i < v.Len(); i++ {
				deepCopyDefaults(v.Index(i))
			}
		}
	case reflect.Map:
		if !v.IsNil() {
			newMap := reflect.MakeMap(v.Type())
			for _, key := range v.MapKeys() {
				origVal := v.MapIndex(key)
				// 对 map 值进行深拷贝：复制到可寻址变量后递归处理
				valCopy := reflect.New(origVal.Type()).Elem()
				valCopy.Set(origVal)
				deepCopyDefaults(valCopy)
				newMap.SetMapIndex(key, valCopy)
			}
			v.Set(newMap)
		}
	case reflect.Array:
		// 数组容器：与切片相同处理，递归深拷贝每个元素内的引用字段。
		// 数组本身是值类型无需新建，但元素内的指针/切片/map 需断开共享。
		for i := 0; i < v.Len(); i++ {
			deepCopyDefaults(v.Index(i))
		}
	case reflect.Interface:
		// 接口（any）字段：非 nil 时复制动态值到可寻址变量，递归深拷贝后回写接口字段。
		// 与 hasRefFields 的 Interface 分支对齐，消除“白名单不放开 any”的隐式约定
		if !v.IsNil() {
			newVal := reflect.New(v.Elem().Type()).Elem()
			newVal.Set(v.Elem())
			deepCopyDefaults(newVal)
			v.Set(newVal)
		}
	default:
		return
	}
}

// hasRefFields 扫描结构体树，判断是否存在非 nil 的指针、切片或 map 字段。
// 用于注册阶段预计算 needsDeepCopy：若 defaultReq 中存在非 nil 引用字段，
// 则请求阶段需要深拷贝以断开共享。string/int 等不可变值类型不触发。
func hasRefFields(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			if hasRefFields(v.Field(i)) {
				return true
			}
		}
		return false
	case reflect.Ptr:
		if v.IsNil() {
			return false
		}
		return true
	case reflect.Slice:
		return !v.IsNil()
	case reflect.Map:
		return !v.IsNil()
	case reflect.Array:
		// 数组本身是值类型，但元素内可能含引用字段
		for i := 0; i < v.Len(); i++ {
			if hasRefFields(v.Index(i)) {
				return true
			}
		}
		return false
	case reflect.Interface:
		// 接口（any）字段：非 nil 时递归扫描动态值（与 deepCopyDefaults 的 Interface 分支对齐），
		// 消除“白名单不放开 any”的隐式约定
		if v.IsNil() {
			return false
		}
		return hasRefFields(v.Elem())
	default:
		return false
	}
}

// hasRequestPhaseDefaults 判断结构体类型树中是否存在带 default 标签的指针字段。
// 请求阶段 applyDefaults 仅填充 nil 指针字段，若类型树中不存在此类字段，
// 则请求阶段无需调用 applyDefaults，避免无意义的递归遍历。
// visiting 用于自引用循环检测，顶层调用传 nil（函数内部自动初始化）。
// 递归规则：
//   - 指针字段：检查自身是否有 default（有则请求阶段可能需填充），再递归进入目标
//     （因 nil 指针在请求阶段被跳过，非 nil 指针目标已在注册阶段处理）
//   - 值结构体字段：总是可达，递归进入
//   - 切片/数组：元素由 JSON 绑定动态创建，可能含 nil 指针字段，递归进入元素类型
//   - Map：值由 JSON 绑定动态创建，可能含 nil 指针字段，递归进入值类型
func hasRequestPhaseDefaults(t reflect.Type, visiting map[reflect.Type]bool) bool {
	t = derefType(t)
	// 顶层或经指针递归到达的切片/map：穿透到元素/值类型继续检测
	switch t.Kind() {
	case reflect.Slice, reflect.Array:
		return hasRequestPhaseDefaults(t.Elem(), visiting)
	case reflect.Map:
		return hasRequestPhaseDefaults(t.Elem(), visiting)
	default:
	}
	if t.Kind() != reflect.Struct {
		return false
	}
	if visiting == nil {
		visiting = make(map[reflect.Type]bool)
	}
	if visiting[t] {
		return false // 自引用循环，停止递归
	}
	visiting[t] = true
	defer delete(visiting, t)

	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue
		}
		if f.Anonymous && f.Type == metaType {
			continue
		}

		ft := f.Type
		switch ft.Kind() {
		case reflect.Ptr:
			// 指针字段自身带 default → 请求阶段可能需要填充 nil 指针
			if _, ok := f.Tag.Lookup("default"); ok {
				if isDefaultSupported(ft) {
					return true
				}
			}
			// 递归进入指针目标类型（非 nil 时其内部可能还有带 default 的指针字段）
			if hasRequestPhaseDefaults(ft.Elem(), visiting) {
				return true
			}
		case reflect.Struct:
			// 值结构体字段总是可达（不会被 JSON 绑定置 nil），递归进入
			if hasRequestPhaseDefaults(ft, visiting) {
				return true
			}
		case reflect.Slice, reflect.Array:
			// 切片元素由 JSON 绑定动态创建，可能含 nil 指针字段
			if hasRequestPhaseDefaults(ft.Elem(), visiting) {
				return true
			}
		case reflect.Map:
			// Map 值由 JSON 绑定动态创建，可能含 nil 指针字段
			if hasRequestPhaseDefaults(ft.Elem(), visiting) {
				return true
			}
		default:
			// Interface / Func / Chan / UnsafePointer 等无法反射出 struct，无需处理
		}
	}
	return false
}

// isDefaultSupported 判定字段类型是否支持 default 标签：仅标量类型及其切片支持
func isDefaultSupported(t reflect.Type) bool {
	return isDefaultSupportedDepth(t, 0)
}

// isDefaultSupportedDepth 带深度上限的递归实现，
// 防自引用命名类型（如 type S []S）无限递归，超限视为不支持
func isDefaultSupportedDepth(t reflect.Type, depth int) bool {
	if depth >= maxPtrDerefDepth {
		return false
	}
	switch t.Kind() {
	case reflect.String, reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return true
	case reflect.Slice, reflect.Ptr:
		return isDefaultSupportedDepth(t.Elem(), depth+1)
	default:
		return false
	}
}
